aspnet/mvc/views/working-with-forms/sample/final/Controllers/DemoController.cs
using FormsTagHelper.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FormsTagHelper.Controllers
{
    // This controller is used only to demonstrate working with forms.

    public class DemoController : Controller
    {       
        public IActionResult Index(string id)
        {
            ViewData["Message"] = id;
            return View();
        }

        public IActionResult RegisterTextArea()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RegisterTextArea(DescriptionViewModel model)
        {
            if (ModelState.IsValid)
            {
                var success = "HttpPost Register success " + model.Description;
                return RedirectToAction("Index", new { id = success });
            }

            return View(model);
        }

        public IActionResult RegisterFormOnly()
        {
            return View();
        }

        public IActionResult RegisterInput()
        {
            return View();
        }

        public IActionResult RegisterAddress()
        {
            return View();
        }

        public IActionResult RegisterValidation()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RegisterValidation(ViewModels.RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var success = "HttpPost Register success " + model.Email;
                return RedirectToAction("Index", new { id = success });
            }

            return View(model);
        }

        public IActionResult RegisterLabel()
        {
            return View();
        }
    }
}

aspnet/mvc/views/working-with-forms/sample/final/Views/Demo/Edit.cshtml
@model List<ToDoItem>

<form asp-controller="ToDo" asp-action="Edit" method="post">
    <table>
        <tr> <th>Name</th> <th>Is Done</th> </tr>

        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                @Html.EditorFor(model => model[i])
            </tr>
        }

    </table>
    <button type="submit">Save</button>
</form>

aspnet/mvc/views/working-with-forms/sample/final/Views/Demo/EditColor.cshtml
@model Person
@{
    var index = (int)ViewData["index"];
}

<form asp-controller="ToDo" asp-action="Edit" method="post">
    @Html.EditorFor(m => m.Colors[index])
    <label asp-for="Age"></label>
    <input asp-for="Age" /><br />
    <button type="submit">Post</button>
</form>

aspnet/mvc/views/working-with-forms/sample/final/Views/Demo/Index.cshtml
<h1> Index Page</h1>

<h3>@ViewData["Message"]</h3>

aspnet/mvc/views/working-with-forms/sample/final/Views/Demo/RegisterAddress.cshtml
@model RegisterAddressViewModel

<form asp-controller="Demo" asp-action="RegisterAddress" method="post">
    Email:  <input asp-for="Email" /> <br />
    Password: <input asp-for="Password" /><br />
    Address: <input asp-for="Address.AddressLine1" /><br />
    <button type="submit">Register</button>
</form>

aspnet/mvc/views/working-with-forms/sample/final/Views/Demo/RegisterFormOnly.cshtml
<form asp-controller="Demo" asp-action="Register" method="post">
    <!-- Input and Submit elements -->
</form>

aspnet/mvc/views/working-with-forms/sample/final/Views/Demo/RegisterInput.cshtml
@model RegisterViewModel

<form asp-controller="Demo" asp-action="RegisterInput" method="post">
    Email:  <input asp-for="Email" /> <br />
    Password: <input asp-for="Password" /><br />
    <button type="submit">Register</button>
</form>

aspnet/mvc/views/working-with-forms/sample/final/Views/Demo/RegisterLabel.cshtml
@model SimpleViewModel

<form asp-controller="Demo" asp-action="RegisterLabel" method="post">
    <label asp-for="Email"></label>
    <input asp-for="Email" /> <br />
</form>

aspnet/mvc/views/working-with-forms/sample/final/Views/Demo/RegisterRoute.cshtml
<form asp-route="register" method="post">
    <!-- Input and Submit elements -->
</form>

aspnet/mvc/views/working-with-forms/sample/final/Views/Demo/RegisterTextArea.cshtml
@model DescriptionViewModel

<form asp-controller="Demo" asp-action="RegisterTextArea" method="post">
    <textarea asp-for="Description"></textarea>
    <button type="submit">Test</button>
</form>

aspnet/mvc/views/working-with-forms/sample/final/Views/Demo/RegisterValidation.cshtml
@model RegisterViewModel

<form asp-controller="Demo" asp-action="RegisterValidation" method="post">
    <div asp-validation-summary="ValidationSummary.ModelOnly"></div>
    Email:  <input asp-for="Email" /> <br />
    <span asp-validation-for="Email"></span><br />
    Password: <input asp-for="Password" /><br />
    <span asp-validation-for="Password"></span><br />
    <button type="submit">Register</button>
</form>

<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js">
</script>
<script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js">
</script>